import '../styles/globals.css'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'

function MyApp({ Component, pageProps }) {
  return <>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.1/dist/flowbite.min.css" />
        <script src="https://unpkg.com/flowbite@1.4.1/dist/flowbite.js"></script>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Component {...pageProps} />
      </main>
    </div>

  </>
}

export default MyApp
